// Cloudflare Worker for the DFT SJT Mock Paper.
// Serves the static site from ./docs and a small anonymous API backed by D1:
//   POST /api/answers   first-attempt answers, keyed by a random client id
//   GET  /api/stats?q=N how everyone answered question N
//   POST /api/feedback  "I disagree with this key", with an optional comment
// No names, emails or IP addresses are stored. IPs are only hashed into hourly rate-limit buckets.

// Question types in order: r = ranking (5 options), b = best three of eight. Regenerated by tools/build.js.
// TYPES:start
const QTYPES = "rbrrbrrbrbrbrbrrrbrbrbrbrbrrrbbrrbrbrrbrbrbrbrbrbrrbrbrbrbrbrrbrrrbrbrrbrbrbrbbbrrrbrbrbrbrrrbrb";
// TYPES:end

const CORS_ORIGINS = ["https://sajeev2112.github.io"];
const HOURLY_LIMIT = 400;
const MIN_STATS = 3;

let schemaReady = false;
const SCHEMA = [
  "CREATE TABLE IF NOT EXISTS answers (client TEXT NOT NULL, q INTEGER NOT NULL, a TEXT NOT NULL, t INTEGER NOT NULL, PRIMARY KEY (client, q))",
  "CREATE INDEX IF NOT EXISTS answers_q ON answers (q)",
  "CREATE TABLE IF NOT EXISTS feedback (client TEXT NOT NULL, q INTEGER NOT NULL, comment TEXT, t INTEGER NOT NULL, PRIMARY KEY (client, q))",
  "CREATE INDEX IF NOT EXISTS feedback_q ON feedback (q)",
  "CREATE TABLE IF NOT EXISTS hits (k TEXT PRIMARY KEY, h INTEGER NOT NULL, n INTEGER NOT NULL)"
];

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith("/api/")) return env.ASSETS.fetch(request);

    const cors = corsHeaders(request);
    if (request.method === "OPTIONS") return new Response(null, {status: 204, headers: cors});
    if (!env.DB) return json({error: "not_configured"}, 503, cors);

    try {
      if (!schemaReady) { await env.DB.batch(SCHEMA.map(s => env.DB.prepare(s))); schemaReady = true; }
      if (url.pathname === "/api/stats" && request.method === "GET") return await stats(url, env, cors);
      if (url.pathname === "/api/answers" && request.method === "POST") return await answers(request, env, ctx, cors);
      if (url.pathname === "/api/feedback" && request.method === "POST") return await feedback(request, env, ctx, cors);
      return json({error: "not_found"}, 404, cors);
    } catch (err) {
      console.error(err);
      return json({error: "server_error"}, 500, cors);
    }
  }
};

async function stats(url, env, cors) {
  const q = toQ(url.searchParams.get("q"));
  if (!q) return json({error: "bad_question"}, 400, cors);
  const type = QTYPES[q - 1];
  const [rows, fb] = await env.DB.batch([
    env.DB.prepare("SELECT a, COUNT(*) AS c FROM answers WHERE q = ? GROUP BY a").bind(q),
    env.DB.prepare("SELECT COUNT(*) AS c FROM feedback WHERE q = ?").bind(q)
  ]);
  let n = 0;
  const out = {q, type, n: 0, min: MIN_STATS, disagree: fb.results[0]?.c || 0};
  if (type === "r") {
    const pos = Array.from({length: 5}, () => [0, 0, 0, 0, 0]);
    for (const {a, c} of rows.results) {
      if (!validAnswer(type, a)) continue;
      n += c;
      for (let p = 0; p < 5; p++) pos[+a[p]][p] += c;
    }
    if (n >= MIN_STATS) out.pos = pos;
  } else {
    const pick = [0, 0, 0, 0, 0, 0, 0, 0];
    for (const {a, c} of rows.results) {
      if (!validAnswer(type, a)) continue;
      n += c;
      for (const ch of a) pick[+ch] += c;
    }
    if (n >= MIN_STATS) out.pick = pick;
  }
  out.n = n;
  return json(out, 200, {...cors, "Cache-Control": "public, max-age=30"});
}

async function answers(request, env, ctx, cors) {
  const body = await readJson(request, 16384);
  if (!body || !validClient(body.client) || !Array.isArray(body.items)) return json({error: "bad_request"}, 400, cors);
  const items = [];
  for (const it of body.items.slice(0, 100)) {
    const q = toQ(it && it.q);
    if (q && typeof it.a === "string" && validAnswer(QTYPES[q - 1], it.a)) items.push([q, it.a]);
  }
  if (!items.length) return json({ok: true, stored: 0}, 200, cors);
  if (!(await allow(request, env, ctx, items.length))) return json({error: "rate_limited"}, 429, cors);
  const now = Date.now();
  await env.DB.batch(items.map(([q, a]) =>
    env.DB.prepare("INSERT OR IGNORE INTO answers (client, q, a, t) VALUES (?, ?, ?, ?)").bind(body.client, q, a, now)));
  return json({ok: true, stored: items.length}, 200, cors);
}

async function feedback(request, env, ctx, cors) {
  const body = await readJson(request, 4096);
  const q = toQ(body && body.q);
  if (!body || !validClient(body.client) || !q) return json({error: "bad_request"}, 400, cors);
  let comment = typeof body.comment === "string" ? body.comment : "";
  comment = comment.replace(/[\u0000-\u0008\u000B-\u001F\u007F]/g, "").trim().slice(0, 500);
  if (!(await allow(request, env, ctx, 5))) return json({error: "rate_limited"}, 429, cors);
  await env.DB.prepare(
    "INSERT INTO feedback (client, q, comment, t) VALUES (?, ?, ?, ?) ON CONFLICT (client, q) DO UPDATE SET comment = excluded.comment, t = excluded.t"
  ).bind(body.client, q, comment || null, Date.now()).run();
  return json({ok: true}, 200, cors);
}

// Hourly rate limit per hashed IP. Old buckets are pruned occasionally.
async function allow(request, env, ctx, weight) {
  const ip = request.headers.get("CF-Connecting-IP") || "unknown";
  const hour = Math.floor(Date.now() / 3600000);
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(ip + "|dft-sjt|" + hour));
  const key = [...new Uint8Array(digest).slice(0, 12)].map(b => b.toString(16).padStart(2, "0")).join("");
  const row = await env.DB.prepare(
    "INSERT INTO hits (k, h, n) VALUES (?, ?, ?) ON CONFLICT (k) DO UPDATE SET n = n + excluded.n RETURNING n"
  ).bind(key, hour, weight).first();
  if (Math.random() < 0.02) ctx.waitUntil(env.DB.prepare("DELETE FROM hits WHERE h < ?").bind(hour - 24).run());
  return !row || row.n <= HOURLY_LIMIT;
}

function toQ(v) {
  const q = Number(v);
  return Number.isInteger(q) && q >= 1 && q <= QTYPES.length ? q : 0;
}
function validClient(c) { return typeof c === "string" && /^[A-Za-z0-9-]{8,64}$/.test(c); }
function validAnswer(type, a) {
  if (typeof a !== "string") return false;
  if (type === "r") return /^[0-4]{5}$/.test(a) && new Set(a).size === 5;
  if (type === "b") return /^[0-7]{3}$/.test(a) && new Set(a).size === 3;
  return false;
}
async function readJson(request, max) {
  const text = await request.text();
  if (text.length > max) return null;
  try { return JSON.parse(text); } catch { return null; }
}
function corsHeaders(request) {
  const origin = request.headers.get("Origin");
  if (!origin || !CORS_ORIGINS.includes(origin)) return {};
  return {"Access-Control-Allow-Origin": origin, "Access-Control-Allow-Methods": "GET, POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type", "Vary": "Origin"};
}
function json(data, status, headers) {
  return new Response(JSON.stringify(data), {status, headers: {"Content-Type": "application/json; charset=utf-8", "X-Content-Type-Options": "nosniff", ...headers}});
}
