// Cloudflare Worker for the DFT SJT Mock Paper.
// Serves the static site from ./docs and a small anonymous API backed by D1:
//   POST /api/answers   first-attempt answers, keyed by a random client id
//   GET  /api/stats?q=N how everyone answered question N
//   POST /api/feedback  "I disagree with this key", with an optional comment
//   POST /api/visit     one anonymous visit per page load (private visitor stats, read in the D1 console)
//   POST /api/error     a browser error report (message only)
//   POST /api/sync      save, load or delete progress under a username + PIN (optional cross-device sync; no accounts)
//   GET  /api/admin     private dashboard data; needs "Authorization: Bearer <ADMIN_KEY>" (a Worker secret)
//   GET  /api/health    uptime check used by the GitHub Actions alert workflow (counts only, no messages)
// Answers and feedback use the _v2 tables since the question bank was rewritten (Sept 2026); the old tables are kept but unused.
// No names, emails or IP addresses are stored. IPs are only hashed into hourly rate-limit buckets.

// Question types in order: r = ranking (5 options), b = best three of eight. Regenerated by tools/build.js.
// TYPES:start
const QTYPES = "rbrrbrrbrbrbrbrrrbrbrbrbrbrrrbbrrbrbrrbrbrbrbrbrbrrbrbrbrbrbrrbrrrbrbrrbrbrbrbbbrrrbrbrbrbrrrbrbrbrrrrbrbrrrbrrrbrbrrbrrbrbrbrbrrbrrrbrrrrbrrbrrbrrrbrbrbrrbrrrb";
// TYPES:end

const CORS_ORIGINS = ["https://sajeev2112.github.io"];
// Hourly limits per network and endpoint. Generous enough for a whole class on shared Wi-Fi.
const LIMITS = {answers: 3000, feedback: 100, visit: 600, error: 20, admin: 60, sync: 600, create: 20};
const MIN_STATS = 3;

let schemaReady = false;
const SCHEMA = [
  "CREATE TABLE IF NOT EXISTS answers_v2 (client TEXT NOT NULL, q INTEGER NOT NULL, a TEXT NOT NULL, t INTEGER NOT NULL, PRIMARY KEY (client, q))",
  "CREATE INDEX IF NOT EXISTS answers_v2_q ON answers_v2 (q)",
  "CREATE TABLE IF NOT EXISTS feedback_v2 (client TEXT NOT NULL, q INTEGER NOT NULL, comment TEXT, t INTEGER NOT NULL, PRIMARY KEY (client, q))",
  "CREATE INDEX IF NOT EXISTS feedback_v2_q ON feedback_v2 (q)",
  "CREATE TABLE IF NOT EXISTS hits (k TEXT PRIMARY KEY, h INTEGER NOT NULL, n INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS visits (day TEXT NOT NULL, client TEXT NOT NULL, views INTEGER NOT NULL, app INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (day, client))",
  "CREATE TABLE IF NOT EXISTS errors (t INTEGER NOT NULL, kind TEXT NOT NULL, msg TEXT)",
  "CREATE INDEX IF NOT EXISTS errors_t ON errors (t)",
  "CREATE TABLE IF NOT EXISTS sync (name TEXT PRIMARY KEY, salt TEXT NOT NULL, pin TEXT NOT NULL, data TEXT, ts INTEGER NOT NULL DEFAULT 0, updated INTEGER NOT NULL, fails INTEGER NOT NULL DEFAULT 0, locked_until INTEGER NOT NULL DEFAULT 0)",
  // Running totals for community stats, kept up to date as answers arrive, so a stats lookup reads
  // at most 120 rows however many people have answered (instead of recounting every answer).
  "CREATE TABLE IF NOT EXISTS answer_counts (q INTEGER NOT NULL, a TEXT NOT NULL, c INTEGER NOT NULL, PRIMARY KEY (q, a))",
  "CREATE TRIGGER IF NOT EXISTS answers_v2_count AFTER INSERT ON answers_v2 BEGIN INSERT INTO answer_counts (q, a, c) VALUES (NEW.q, NEW.a, 1) ON CONFLICT (q, a) DO UPDATE SET c = c + 1; END"
];

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith("/api/")) return env.ASSETS.fetch(request);

    const cors = corsHeaders(request);
    if (request.method === "OPTIONS") return new Response(null, {status: 204, headers: cors});
    // Writes only from this site: other websites can't spend their visitors' networks on the API.
    if (request.method === "POST" && !sameSite(request, url)) return json({error: "forbidden"}, 403, cors);
    if (!env.DB) return json({error: "not_configured"}, 503, cors);

    try {
      if (!schemaReady) {
        await env.DB.batch(SCHEMA.map(s => env.DB.prepare(s)));
        // one-off: build the totals from answers stored before they existed
        if (!(await env.DB.prepare("SELECT 1 AS x FROM answer_counts LIMIT 1").first()))
          await env.DB.prepare("INSERT INTO answer_counts (q, a, c) SELECT q, a, COUNT(*) FROM answers_v2 WHERE NOT EXISTS (SELECT 1 FROM answer_counts) GROUP BY q, a").run();
        schemaReady = true;
      }
      if (url.pathname === "/api/stats" && request.method === "GET") return await stats(url, env, cors);
      if (url.pathname === "/api/answers" && request.method === "POST") return await answers(request, env, ctx, cors);
      if (url.pathname === "/api/feedback" && request.method === "POST") return await feedback(request, env, ctx, cors);
      if (url.pathname === "/api/visit" && request.method === "POST") return await visit(request, env, ctx, cors);
      if (url.pathname === "/api/error" && request.method === "POST") return await clientError(request, env, ctx, cors);
      if (url.pathname === "/api/health" && request.method === "GET") return await health(env, cors);
      if (url.pathname === "/api/sync" && request.method === "POST") return await sync(request, env, ctx, cors);
      if (url.pathname === "/api/admin" && request.method === "GET") return await admin(request, env, ctx, cors);
      return json({error: "not_found"}, 404, cors);
    } catch (err) {
      console.error(err);
      ctx.waitUntil(env.DB.prepare("INSERT INTO errors (t, kind, msg) VALUES (?, ?, ?)").bind(Date.now(), "server", String(err && err.message || err).slice(0, 300)).run().catch(() => {}));
      return json({error: "server_error"}, 500, cors);
    }
  }
};

async function stats(url, env, cors) {
  const q = toQ(url.searchParams.get("q"));
  if (!q) return json({error: "bad_question"}, 400, cors);
  const type = QTYPES[q - 1];
  const [rows, fb] = await env.DB.batch([
    env.DB.prepare("SELECT a, c FROM answer_counts WHERE q = ?").bind(q),
    env.DB.prepare("SELECT COUNT(*) AS c FROM feedback_v2 WHERE q = ?").bind(q)
  ]);
  let n = 0;
  const out = {q, type, n: 0, min: MIN_STATS, disagree: fb.results[0]?.c || 0};
  if (type === "r") {
    const pos = Array.from({length: 5}, () => [0, 0, 0, 0, 0]);
    for (const {a, c} of rows.results) {
      if (!validAnswer(type, a)) continue;
      n += c;
      for (let p = 0; p < 5; p++) pos[+a[p]][p] += c;
    }
    if (n >= MIN_STATS) out.pos = pos;
  } else {
    const pick = [0, 0, 0, 0, 0, 0, 0, 0];
    for (const {a, c} of rows.results) {
      if (!validAnswer(type, a)) continue;
      n += c;
      for (const ch of a) pick[+ch] += c;
    }
    if (n >= MIN_STATS) out.pick = pick;
  }
  out.n = n;
  return json(out, 200, {...cors, "Cache-Control": "public, max-age=30"});
}

async function answers(request, env, ctx, cors) {
  const body = await readJson(request, 16384);
  if (!body || !validClient(body.client) || !Array.isArray(body.items)) return json({error: "bad_request"}, 400, cors);
  const items = [], seen = new Set();
  for (const it of body.items.slice(0, 100)) {
    const q = toQ(it && it.q);
    if (q && !seen.has(q) && typeof it.a === "string" && validAnswer(QTYPES[q - 1], it.a)) { seen.add(q); items.push([q, it.a]); }
  }
  if (!items.length) return json({ok: true, stored: 0}, 200, cors);
  if (!(await allow(request, env, ctx, items.length, "answers"))) return json({error: "rate_limited"}, 429, cors);
  const now = Date.now();
  await env.DB.batch(items.map(([q, a]) =>
    env.DB.prepare("INSERT OR IGNORE INTO answers_v2 (client, q, a, t) VALUES (?, ?, ?, ?)").bind(body.client, q, a, now)));
  return json({ok: true, stored: items.length}, 200, cors);
}

async function feedback(request, env, ctx, cors) {
  const body = await readJson(request, 4096);
  const q = toQ(body && body.q);
  if (!body || !validClient(body.client) || !q) return json({error: "bad_request"}, 400, cors);
  let comment = typeof body.comment === "string" ? body.comment : "";
  comment = comment.replace(/[\u0000-\u0008\u000B-\u001F\u007F]/g, "").trim().slice(0, 500);
  if (!(await allow(request, env, ctx, 1, "feedback"))) return json({error: "rate_limited"}, 429, cors);
  await env.DB.prepare(
    "INSERT INTO feedback_v2 (client, q, comment, t) VALUES (?, ?, ?, ?) ON CONFLICT (client, q) DO UPDATE SET comment = excluded.comment, t = excluded.t"
  ).bind(body.client, q, comment || null, Date.now()).run();
  return json({ok: true}, 200, cors);
}

async function visit(request, env, ctx, cors) {
  const body = await readJson(request, 1024);
  if (!body || !validClient(body.client)) return json({error: "bad_request"}, 400, cors);
  if (!(await allow(request, env, ctx, 1, "visit"))) return json({error: "rate_limited"}, 429, cors);
  const day = new Date().toISOString().slice(0, 10);
  await env.DB.prepare(
    "INSERT INTO visits (day, client, views, app) VALUES (?, ?, 1, ?) ON CONFLICT (day, client) DO UPDATE SET views = views + 1, app = MAX(app, excluded.app)"
  ).bind(day, body.client, body.app ? 1 : 0).run();
  return json({ok: true}, 200, cors);
}

async function clientError(request, env, ctx, cors) {
  const body = await readJson(request, 2048);
  if (!body || typeof body.msg !== "string") return json({error: "bad_request"}, 400, cors);
  if (!(await allow(request, env, ctx, 1, "error"))) return json({error: "rate_limited"}, 429, cors);
  const since = Date.now() - 3600000;
  const recent = await env.DB.prepare("SELECT COUNT(*) AS c FROM errors WHERE kind = ? AND t > ?").bind("client", since).first();
  if ((recent && recent.c) < 200) {
    const msg = body.msg.replace(/[\u0000-\u001F\u007F]/g, " ").slice(0, 300);
    await env.DB.prepare("INSERT INTO errors (t, kind, msg) VALUES (?, ?, ?)").bind(Date.now(), "client", msg).run();
  }
  return json({ok: true}, 200, cors);
}

async function health(env, cors) {
  const now = Date.now(), h1 = now - 3600000, h24 = now - 86400000;
  const r = await env.DB.prepare(
    "SELECT SUM(kind = 'server' AND t > ?1) AS s1, SUM(kind = 'client' AND t > ?1) AS c1, SUM(kind = 'server' AND t > ?2) AS s24, SUM(kind = 'client' AND t > ?2) AS c24 FROM errors WHERE t > ?2"
  ).bind(h1, h24).first();
  if (Math.random() < 0.05) await env.DB.prepare("DELETE FROM errors WHERE t < ?").bind(now - 30 * 86400000).run();
  return json({ok: true, db: true, errors: {server_1h: r?.s1 || 0, client_1h: r?.c1 || 0, server_24h: r?.s24 || 0, client_24h: r?.c24 || 0}}, 200, {...cors, "Cache-Control": "no-store"});
}

// Optional cross-device sync. A username plus a 4–8 digit PIN; the PIN is stored salted and hashed.
// Wrong PINs lock the name for 15 minutes after every 5 failures, doubling each time.
const SYNC_MAX = 262144;
async function sync(request, env, ctx, cors) {
  const noStore = {...cors, "Cache-Control": "no-store"};
  const body = await readJson(request, SYNC_MAX * 2 + 2048); // the progress JSON is string-escaped inside the body
  if (!body) return json({error: "bad_request"}, 400, noStore);
  const name = typeof body.name === "string" ? body.name.trim().toLowerCase() : "";
  const pin = typeof body.pin === "string" ? body.pin : "";
  if (!/^[a-z0-9][a-z0-9_.-]{2,29}$/.test(name)) return json({error: "bad_name"}, 400, noStore);
  if (!/^\d{4,8}$/.test(pin)) return json({error: "bad_pin"}, 400, noStore);
  if (!["save", "load", "delete"].includes(body.action)) return json({error: "bad_action"}, 400, noStore);
  if (!(await allow(request, env, ctx, 1, "sync"))) return json({error: "rate_limited"}, 429, noStore);
  const now = Date.now();
  const okTs = v => { const n = Number(v); return Number.isSafeInteger(n) && n > 0 && n <= now + 86400000 ? n : 0; };
  let row = await env.DB.prepare("SELECT * FROM sync WHERE name = ?").bind(name).first();

  if (!row) {
    // An unknown name answers like a wrong PIN, so names can't be discovered by probing.
    if (body.action !== "save") return json({error: "wrong_pin"}, 401, noStore);
    const data = typeof body.data === "string" ? body.data : "";
    if (!data || data.length > SYNC_MAX) return json({error: "bad_data"}, 400, noStore);
    if (!(await allow(request, env, ctx, 1, "create"))) return json({error: "rate_limited"}, 429, noStore);
    const salt = randomHex(16), ts = okTs(body.ts) || now;
    const made = await env.DB.prepare("INSERT INTO sync (name, salt, pin, data, ts, updated) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (name) DO NOTHING RETURNING name")
      .bind(name, salt, await pinHash(salt, pin), data, ts, now).first();
    if (made) return json({ok: true, created: true, ts}, 200, noStore);
    row = await env.DB.prepare("SELECT * FROM sync WHERE name = ?").bind(name).first(); // created by a simultaneous request
    if (!row) return json({error: "server_busy"}, 503, noStore);
  }

  if (row.locked_until > now) return json({error: "locked", retry_after: Math.ceil((row.locked_until - now) / 60000)}, 423, noStore);
  if (!(await sameSecret(await pinHash(row.salt, pin), row.pin))) {
    // One atomic update, so simultaneous guesses can't all read the same failure count and dodge the lock.
    const f = await env.DB.prepare("UPDATE sync SET fails = fails + 1, locked_until = CASE WHEN (fails + 1) % 5 = 0 THEN ?1 + 900000 * (1 << min(6, (fails + 1) / 5 - 1)) ELSE locked_until END WHERE name = ?2 RETURNING fails, locked_until")
      .bind(now, name).first();
    return json({error: "wrong_pin", locked: !!(f && f.locked_until > now)}, 401, noStore);
  }
  // A right PIN only counts if the name wasn't locked by guesses that landed first.
  const open = await env.DB.prepare("UPDATE sync SET fails = 0, locked_until = 0 WHERE name = ?1 AND locked_until <= ?2 RETURNING name").bind(name, now).first();
  if (!open) { const l = await env.DB.prepare("SELECT locked_until FROM sync WHERE name = ?").bind(name).first(); return json({error: "locked", retry_after: Math.max(1, Math.ceil(((l && l.locked_until) - now) / 60000))}, 423, noStore); }

  if (body.action === "load") return json({ok: true, data: row.data, ts: row.ts, updated: row.updated}, 200, noStore);
  if (body.action === "delete") { await env.DB.prepare("DELETE FROM sync WHERE name = ?").bind(name).run(); return json({ok: true, deleted: true}, 200, noStore); }

  // save: refuse to overwrite a copy that another device saved after this one last synced, unless forced
  const data = typeof body.data === "string" ? body.data : "";
  if (!data || data.length > SYNC_MAX) return json({error: "bad_data"}, 400, noStore);
  const base = okTs(body.base);
  if (!body.force && row.ts > base) return json({error: "conflict", ts: row.ts, updated: row.updated}, 409, noStore);
  const ts = okTs(body.ts) || now;
  await env.DB.prepare("UPDATE sync SET data = ?, ts = ?, updated = ? WHERE name = ?").bind(data, ts, now, name).run();
  return json({ok: true, ts}, 200, noStore);
}
async function pinHash(salt, pin) {
  const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(salt + "|dft-sjt-sync|" + pin));
  return [...new Uint8Array(d)].map(b => b.toString(16).padStart(2, "0")).join("");
}
function randomHex(n) { const a = new Uint8Array(n); crypto.getRandomValues(a); return [...a].map(b => b.toString(16).padStart(2, "0")).join(""); }

// Private dashboard data. The password is the ADMIN_KEY secret set in the Cloudflare dashboard.
async function admin(request, env, ctx, cors) {
  const noStore = {...cors, "Cache-Control": "no-store"};
  if (!env.ADMIN_KEY) return json({error: "admin_not_configured"}, 503, noStore);
  if (!(await allow(request, env, ctx, 1, "admin"))) return json({error: "rate_limited"}, 429, noStore);
  const given = (request.headers.get("Authorization") || "").replace(/^Bearer\s+/i, "");
  if (!(await sameSecret(given, env.ADMIN_KEY))) return json({error: "unauthorised"}, 401, noStore);
  const q = sql => env.DB.prepare(sql);
  const [visits, totals, answersByDay, dist, feedback, errors] = await env.DB.batch([
    q("SELECT day, COUNT(*) AS visitors, SUM(views) AS views, SUM(app) AS app FROM visits GROUP BY day ORDER BY day DESC LIMIT 120"),
    q("SELECT (SELECT COUNT(DISTINCT client) FROM visits) AS visitors, (SELECT COUNT(*) FROM (SELECT client FROM visits GROUP BY client HAVING COUNT(*) > 1)) AS returning_visitors, (SELECT COUNT(DISTINCT client) FROM visits WHERE app = 1) AS app_users, (SELECT COUNT(DISTINCT client) FROM answers_v2) AS answering, (SELECT COUNT(*) FROM answers_v2) AS answers, (SELECT COUNT(*) FROM feedback_v2) AS feedback"),
    q("SELECT date(t / 1000, 'unixepoch') AS day, COUNT(*) AS answers, COUNT(DISTINCT client) AS people FROM answers_v2 GROUP BY day ORDER BY day DESC LIMIT 120"),
    q("SELECT q, a, COUNT(*) AS c FROM answers_v2 GROUP BY q, a"),
    q("SELECT q, comment, t FROM feedback_v2 ORDER BY t DESC LIMIT 300"),
    q("SELECT t, kind, msg FROM errors ORDER BY t DESC LIMIT 50")
  ]);
  return json({generated: Date.now(), totals: totals.results[0], visits: visits.results.reverse(), answersByDay: answersByDay.results.reverse(),
    distributions: dist.results, feedback: feedback.results, errors: errors.results}, 200, noStore);
}
// Compares secrets via their SHA-256 digests so the check takes the same time whatever is typed.
async function sameSecret(a, b) {
  const enc = new TextEncoder();
  const [x, y] = await Promise.all([crypto.subtle.digest("SHA-256", enc.encode(a)), crypto.subtle.digest("SHA-256", enc.encode(b))]);
  const u = new Uint8Array(x), v = new Uint8Array(y); let diff = 0;
  for (let i = 0; i < u.length; i++) diff |= u[i] ^ v[i];
  return a.length > 0 && diff === 0;
}

// Hourly rate limit per hashed IP (the database fallback). Old buckets are pruned occasionally.
// IPv6 addresses are grouped by /64 (one home or device network) so rotating addresses doesn’t bypass the limit.
function network(ip) {
  if (!ip.includes(":")) return ip;
  if (/^::ffff:\d+\.\d+\.\d+\.\d+$/i.test(ip)) return ip.slice(7); // IPv4-mapped address: treat as IPv4
  const [head, tail] = ip.split("::");
  const h = head ? head.split(":") : [], t = tail !== undefined && tail !== "" ? tail.split(":") : [];
  const groups = tail === undefined ? h : h.concat(Array(Math.max(0, 8 - h.length - t.length)).fill("0"), t);
  return groups.slice(0, 4).map(g => (parseInt(g, 16) || 0).toString(16)).join(":") + "::/64";
}
// Busy endpoints use Cloudflare's built-in rate limiter (per minute, kept outside the database, so no D1 write).
// Rare or security-sensitive ones (new sync names, admin, error reports) keep exact hourly counts in D1.
// If a binding is missing (local tests, or a plan without it) the D1 counter is used instead.
const RATE_BINDINGS = {answers: "RL_ANSWERS", feedback: "RL_FEEDBACK", visit: "RL_VISIT", sync: "RL_SYNC"};
async function allow(request, env, ctx, weight, kind) {
  const ip = network(request.headers.get("CF-Connecting-IP") || "unknown");
  const rl = env[RATE_BINDINGS[kind]];
  if (rl && typeof rl.limit === "function") {
    const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(ip + "|dft-sjt|" + (env.HASH_PEPPER || "") + "|" + kind));
    const key = [...new Uint8Array(d).slice(0, 12)].map(b => b.toString(16).padStart(2, "0")).join("");
    try { return (await rl.limit({key})).success; } catch (e) { /* fall through to the database counter */ }
  }
  const hour = Math.floor(Date.now() / 3600000);
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(ip + "|dft-sjt|" + (env.HASH_PEPPER || "") + "|" + kind + "|" + hour));
  const key = [...new Uint8Array(digest).slice(0, 12)].map(b => b.toString(16).padStart(2, "0")).join("");
  const row = await env.DB.prepare(
    "INSERT INTO hits (k, h, n) VALUES (?, ?, ?) ON CONFLICT (k) DO UPDATE SET n = n + excluded.n RETURNING n"
  ).bind(key, hour, weight).first();
  if (Math.random() < 0.02) ctx.waitUntil(env.DB.prepare("DELETE FROM hits WHERE h < ?").bind(hour - 24).run());
  return !row || row.n <= LIMITS[kind];
}

function toQ(v) {
  const q = Number(v);
  return Number.isInteger(q) && q >= 1 && q <= QTYPES.length ? q : 0;
}
function validClient(c) { return typeof c === "string" && /^[A-Za-z0-9-]{8,64}$/.test(c); }
function validAnswer(type, a) {
  if (typeof a !== "string") return false;
  if (type === "r") return /^[0-4]{5}$/.test(a) && new Set(a).size === 5;
  if (type === "b") return /^[0-7]{3}$/.test(a) && new Set(a).size === 3;
  return false;
}
async function readJson(request, max) {
  const len = Number(request.headers.get("Content-Length"));
  if (len > max) return null; // refuse oversized bodies before reading them
  const text = await request.text();
  if (text.length > max) return null;
  try { return JSON.parse(text); } catch { return null; }
}
function sameSite(request, url) {
  const origin = request.headers.get("Origin");
  return !origin || origin === url.origin || CORS_ORIGINS.includes(origin);
}
function corsHeaders(request) {
  const origin = request.headers.get("Origin");
  if (!origin || !CORS_ORIGINS.includes(origin)) return {"Vary": "Origin"};
  return {"Access-Control-Allow-Origin": origin, "Access-Control-Allow-Methods": "GET, POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type, Authorization", "Vary": "Origin"};
}
function json(data, status, headers) {
  return new Response(JSON.stringify(data), {status, headers: {"Content-Type": "application/json; charset=utf-8", "X-Content-Type-Options": "nosniff", ...headers}});
}
